import { PUTER_MODELS } from './puterClient';

export const CURATED_PROVIDER_MODELS: Record<string, string[]> = {
    mimo: [
        'mimo-v2.6-flash',
        'mimo-v2.6-pro',
        'xiaomi/mimo-v2.6-pro',
        'mimo-v2-flash',
        'mimo-v2-pro',
    ],
    deepseek: [
        'deepseek-chat',
        'deepseek-reasoner',
        'deepseek-coder',
        'deepseek-v4-flash',
        'deepseek-v4-pro',
        'deepseek/deepseek-v4-flash',
        'deepseek/deepseek-v4-pro',
    ],
    groq: [
        'qwen/qwen3.8-27b',
        'deepseek-r1-distill-llama-70b',
        'llama-3.3-70b-versatile',
        'qwen/qwen3.6-27b',
        'openai/gpt-oss-120b',
        'groq/compound',
        'whisper-large-v3',
    ],
    openai: [
        'gpt-6-luna',
        'openai/gpt-6-luna',
        'gpt-4o',
        'gpt-4o-mini',
        'o1',
        'o3-mini',
        'gpt-4-turbo',
        'gpt-3.5-turbo',
    ],
    google: [
        'gemini-3.8-flash',
        'google/gemini-3.8-flash',
        'gemini-2.5-flash',
        'gemini-2.5-pro',
        'gemini-2.0-flash',
        'gemini-1.5-pro',
        'gemini-1.5-flash',
    ],
    vertex: [
        'gemini-2.5-flash',
        'gemini-2.5-pro',
        'gemini-2.0-flash',
        'gemini-1.5-pro',
        'gemini-1.5-flash',
    ],
    vertexai: [
        'gemini-2.5-flash',
        'gemini-2.5-pro',
        'gemini-2.0-flash',
        'gemini-1.5-pro',
        'gemini-1.5-flash',
    ],
    nvidia: [
        'moonshotai/kimi-k3',
        'minimaxai/minimax-m3',
        'meta/llama-3.3-70b-instruct',
        'deepseek-ai/deepseek-v4-flash-0731',
        'google/gemma-4-31b-it',
        'moonshotai/kimi-k2.6',
        'nvidia/llama-3.1-nemotron-70b-instruct',
        'deepseek-ai/deepseek-r1',
        'deepseek-ai/deepseek-v3',
        'qwen/qwen3-235b-a22b',
    ],
    mistral: [
        'mistral-large-latest',
        'mistral-medium-latest',
        'mistral-small-latest',
        'codestral-latest',
        'open-mistral-nemo',
        'open-mixtral-8x22b',
        'pixtral-large-latest',
    ],
    cerebras: [
        'llama-3.3-70b',
        'llama-3.1-8b',
        'llama3.3-70b',
        'llama3.1-8b',
    ],
    openrouter: [
        'openrouter/auto',
        'google/gemini-3.8-flash',
        'google/gemini-2.5-flash',
        'deepseek/deepseek-v4-flash',
        'deepseek/deepseek-v4-pro',
        'moonshotai/kimi-k3',
        'glm-5.3-flash',
        'zhipu/glm-5.3-flash',
        'openai/gpt-6-luna',
        'gpt-6-luna',
        'deepseek/deepseek-chat',
        'deepseek/deepseek-r1',
        'anthropic/claude-3.5-sonnet',
        'meta-llama/llama-3.3-70b-instruct',
        'google/gemini-2.0-flash-exp:free',
    ],
    zhipu: [
        'glm-5.3-flash',
        'glm-4-plus',
        'glm-4-air',
        'glm-4-flash',
    ],
    glm: [
        'glm-5.3-flash',
        'glm-4-plus',
        'glm-4-air',
        'glm-4-flash',
    ],
    minimax: [
        'MiniMax-Text-01',
        'abab6.5s-chat',
        'abab6.5-chat',
        'abab6.5g-chat',
        'abab5.5s-chat',
        'abab5.5-chat',
    ],
    moonshot: [
        'moonshot-v1-8k',
        'moonshot-v1-32k',
        'moonshot-v1-128k',
        'kimi-latest',
        'kimi-thinking-preview',
    ],
    kie: [
        'gpt-5-2',
        'gpt-5-2-pro',
        'gpt-5-2-chat-latest',
        'gemini-3-flash',
        'gemini-2.5-flash',
        'gemini-2.5-pro',
        'gemini-2.0-flash',
        'gpt-4o',
        'gpt-4o-mini',
        'o1',
        'o3-mini',
        'claude-3-7-sonnet-20250219',
        'claude-3-5-sonnet-20241022',
        'deepseek-chat',
        'deepseek-reasoner',
        'llama-3.3-70b-versatile',
    ],
    puter: PUTER_MODELS.map(m => m.id),
    zettacore: [
        'arena-claude-opus-4-6',
        'arena-gpt-4o',
        'gemini-web',
        'chatgpt-web',
        'qwen-web',
    ],
    vercel: [
        'openai/gpt-4o',
        'openai/gpt-4o-mini',
        'openai/o1',
        'openai/o3-mini',
        'anthropic/claude-3-7-sonnet-20250219',
        'anthropic/claude-3-5-sonnet-20241022',
        'google/gemini-2.0-flash-001',
        'deepseek/deepseek-chat',
        'deepseek/deepseek-reasoner',
        'meta-llama/llama-3.3-70b-instruct',
    ],
    ollama: [
        'qwen2.5-coder:latest',
        'llama3.2:latest',
        'deepseek-r1:latest',
        'mistral:latest',
    ],
    lmstudio: ['local-model', 'default'],
    vllm: ['default'],
    local: ['default'],
};

export function getCuratedModelsForProvider(provider: string): string[] {
    const norm = (provider || '').toLowerCase().trim();
    if (CURATED_PROVIDER_MODELS[norm]) return [...CURATED_PROVIDER_MODELS[norm]];
    const match = Object.keys(CURATED_PROVIDER_MODELS).find(k => norm.includes(k) || k.includes(norm));
    if (match) return [...CURATED_PROVIDER_MODELS[match]];
    return [];
}
